[package]
name = "dwp"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.45"
gimli = "0.26.1"
memmap = "0.7.0"
object = "0.27.1"
structopt = "0.3.25"
thiserror = "1.0.30"
tracing = "0.1.29"
tracing-subscriber = { version = "0.3.1", features = [ "env-filter" ] }
typed-arena = "2.0.1"
